FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

RUN apt-get update && \
    apt-get install -y zsh time tzdata tree git curl

RUN apt-get update && \
    apt-get install -y gcc-9 g++-9 vim

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 30 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 30 

RUN apt-get install python-matplotlib python-numpy python2.7-dev

WORKDIR /root/files

CMD bash
