FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo

RUN apt-get update && \
    apt-get install -y zsh time tzdata tree git curl

RUN apt-get update && \
    apt-get install -y gcc-9 g++-9 vim

WORKDIR /root/files

CMD bash
